/*** Autogenerated by WIDL 5.0 from ./um/animationcoordinator.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __animationcoordinator_h__
#define __animationcoordinator_h__

/* Forward declarations */

#ifndef __IInputPaneAnimationCoordinator_FWD_DEFINED__
#define __IInputPaneAnimationCoordinator_FWD_DEFINED__
typedef interface IInputPaneAnimationCoordinator IInputPaneAnimationCoordinator;
#ifdef __cplusplus
interface IInputPaneAnimationCoordinator;
#endif /* __cplusplus */
#endif

#ifndef __ShowInputPaneAnimationCoordinator_FWD_DEFINED__
#define __ShowInputPaneAnimationCoordinator_FWD_DEFINED__
#ifdef __cplusplus
typedef class ShowInputPaneAnimationCoordinator ShowInputPaneAnimationCoordinator;
#else
typedef struct ShowInputPaneAnimationCoordinator ShowInputPaneAnimationCoordinator;
#endif /* defined __cplusplus */
#endif /* defined __ShowInputPaneAnimationCoordinator_FWD_DEFINED__ */

#ifndef __HideInputPaneAnimationCoordinator_FWD_DEFINED__
#define __HideInputPaneAnimationCoordinator_FWD_DEFINED__
#ifdef __cplusplus
typedef class HideInputPaneAnimationCoordinator HideInputPaneAnimationCoordinator;
#else
typedef struct HideInputPaneAnimationCoordinator HideInputPaneAnimationCoordinator;
#endif /* defined __cplusplus */
#endif /* defined __HideInputPaneAnimationCoordinator_FWD_DEFINED__ */

/* Headers for imported files */

#include <wtypes.h>
#include <unknwn.h>
#include <dcompanimation.h>

#ifdef __cplusplus
extern "C" {
#endif

//---------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All rights reserved.
//
//---------------------------------------------------------------------------
#include <winapifamily.h>
#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP)
#if (NTDDI_VERSION >= NTDDI_WINBLUE)
/*****************************************************************************
 * IInputPaneAnimationCoordinator interface
 */
#ifndef __IInputPaneAnimationCoordinator_INTERFACE_DEFINED__
#define __IInputPaneAnimationCoordinator_INTERFACE_DEFINED__

DEFINE_GUID(IID_IInputPaneAnimationCoordinator, 0x2af16ba9, 0x2de5, 0x4b75, 0x82,0xd9, 0x01,0x37,0x2a,0xfb,0xff,0xb4);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("2af16ba9-2de5-4b75-82d9-01372afbffb4")
IInputPaneAnimationCoordinator : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE AddAnimation(
        IUnknown *device,
        IDCompositionAnimation *animation) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IInputPaneAnimationCoordinator, 0x2af16ba9, 0x2de5, 0x4b75, 0x82,0xd9, 0x01,0x37,0x2a,0xfb,0xff,0xb4)
#endif
#else
typedef struct IInputPaneAnimationCoordinatorVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IInputPaneAnimationCoordinator *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IInputPaneAnimationCoordinator *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IInputPaneAnimationCoordinator *This);

    /*** IInputPaneAnimationCoordinator methods ***/
    HRESULT (STDMETHODCALLTYPE *AddAnimation)(
        IInputPaneAnimationCoordinator *This,
        IUnknown *device,
        IDCompositionAnimation *animation);

    END_INTERFACE
} IInputPaneAnimationCoordinatorVtbl;

interface IInputPaneAnimationCoordinator {
    CONST_VTBL IInputPaneAnimationCoordinatorVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IInputPaneAnimationCoordinator_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IInputPaneAnimationCoordinator_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IInputPaneAnimationCoordinator_Release(This) (This)->lpVtbl->Release(This)
/*** IInputPaneAnimationCoordinator methods ***/
#define IInputPaneAnimationCoordinator_AddAnimation(This,device,animation) (This)->lpVtbl->AddAnimation(This,device,animation)
#else
/*** IUnknown methods ***/
static FORCEINLINE HRESULT IInputPaneAnimationCoordinator_QueryInterface(IInputPaneAnimationCoordinator* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static FORCEINLINE ULONG IInputPaneAnimationCoordinator_AddRef(IInputPaneAnimationCoordinator* This) {
    return This->lpVtbl->AddRef(This);
}
static FORCEINLINE ULONG IInputPaneAnimationCoordinator_Release(IInputPaneAnimationCoordinator* This) {
    return This->lpVtbl->Release(This);
}
/*** IInputPaneAnimationCoordinator methods ***/
static FORCEINLINE HRESULT IInputPaneAnimationCoordinator_AddAnimation(IInputPaneAnimationCoordinator* This,IUnknown *device,IDCompositionAnimation *animation) {
    return This->lpVtbl->AddAnimation(This,device,animation);
}
#endif
#endif

#endif


#endif  /* __IInputPaneAnimationCoordinator_INTERFACE_DEFINED__ */


DEFINE_GUID(LIBID_AnimationCoordinatorLib, 0xcc15af28, 0x96d8, 0x466f, 0x89,0x3d, 0x16,0x1d,0xa5,0x8c,0xe5,0x1e);

/*****************************************************************************
 * ShowInputPaneAnimationCoordinator coclass
 */

DEFINE_GUID(CLSID_ShowInputPaneAnimationCoordinator, 0x1f046abf, 0x3202, 0x4dc1, 0x8c,0xb5, 0x3c,0x67,0x61,0x7c,0xe1,0xfa);

#ifdef __cplusplus
class DECLSPEC_UUID("1f046abf-3202-4dc1-8cb5-3c67617ce1fa") ShowInputPaneAnimationCoordinator;
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(ShowInputPaneAnimationCoordinator, 0x1f046abf, 0x3202, 0x4dc1, 0x8c,0xb5, 0x3c,0x67,0x61,0x7c,0xe1,0xfa)
#endif
#endif

/*****************************************************************************
 * HideInputPaneAnimationCoordinator coclass
 */

DEFINE_GUID(CLSID_HideInputPaneAnimationCoordinator, 0x384742b1, 0x2a77, 0x4cb3, 0x8c,0xf8, 0x11,0x36,0xf5,0xe1,0x7e,0x59);

#ifdef __cplusplus
class DECLSPEC_UUID("384742b1-2a77-4cb3-8cf8-1136f5e17e59") HideInputPaneAnimationCoordinator;
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(HideInputPaneAnimationCoordinator, 0x384742b1, 0x2a77, 0x4cb3, 0x8c,0xf8, 0x11,0x36,0xf5,0xe1,0x7e,0x59)
#endif
#endif

#endif // (NTDDI_VERSION >= NTDDI_WINBLUE)
#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP) */
/* Begin additional prototypes for all interfaces */


/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __animationcoordinator_h__ */
