/*** Autogenerated by WIDL 5.0 from ./winrt/rdpappcontainerclient.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __rdpappcontainerclient_h__
#define __rdpappcontainerclient_h__

/* Forward declarations */

#ifndef __IRemoteDesktopClientSettings_FWD_DEFINED__
#define __IRemoteDesktopClientSettings_FWD_DEFINED__
typedef interface IRemoteDesktopClientSettings IRemoteDesktopClientSettings;
#ifdef __cplusplus
interface IRemoteDesktopClientSettings;
#endif /* __cplusplus */
#endif

#ifndef __IRemoteDesktopClientActions_FWD_DEFINED__
#define __IRemoteDesktopClientActions_FWD_DEFINED__
typedef interface IRemoteDesktopClientActions IRemoteDesktopClientActions;
#ifdef __cplusplus
interface IRemoteDesktopClientActions;
#endif /* __cplusplus */
#endif

#ifndef __IRemoteDesktopClientTouchPointer_FWD_DEFINED__
#define __IRemoteDesktopClientTouchPointer_FWD_DEFINED__
typedef interface IRemoteDesktopClientTouchPointer IRemoteDesktopClientTouchPointer;
#ifdef __cplusplus
interface IRemoteDesktopClientTouchPointer;
#endif /* __cplusplus */
#endif

#ifndef __IRemoteDesktopClient_FWD_DEFINED__
#define __IRemoteDesktopClient_FWD_DEFINED__
typedef interface IRemoteDesktopClient IRemoteDesktopClient;
#ifdef __cplusplus
interface IRemoteDesktopClient;
#endif /* __cplusplus */
#endif

/* Headers for imported files */

#include <oaidl.h>
#include <ocidl.h>

#ifdef __cplusplus
extern "C" {
#endif

#if (NTDDI_VERSION >= NTDDI_WIN8)
#define DISPID_METHOD_REMOTEDESKTOPCLIENT_CONNECT (701)

#define DISPID_METHOD_REMOTEDESKTOPCLIENT_DISCONNECT (702)

#define DISPID_METHOD_REMOTEDESKTOPCLIENT_RECONNECT (703)

#define DISPID_METHOD_REMOTEDESKTOPCLIENT_DELETE_SAVED_CREDENTIALS (704)

#define DISPID_METHOD_REMOTEDESKTOPCLIENT_UPDATE_SESSION_DISPLAYSETTINGS (705)

#define DISPID_METHOD_REMOTEDESKTOPCLIENT_ATTACH_EVENT (706)

#define DISPID_METHOD_REMOTEDESKTOPCLIENT_DETACH_EVENT (707)

#define DISPID_PROP_REMOTEDESKTOPCLIENT_SETTINGS (710)

#define DISPID_PROP_REMOTEDESKTOPCLIENT_ACTIONS (711)

#define DISPID_PROP_REMOTEDESKTOPCLIENT_TOUCH_POINTER (712)

#define DISPID_METHOD_REMOTEDESKTOPCLIENT_SET_RDPPROPERTY (720)

#define DISPID_METHOD_REMOTEDESKTOPCLIENT_GET_RDPPROPERTY (721)

#define DISPID_METHOD_REMOTEDESKTOPCLIENT_APPLY_SETTINGS (722)

#define DISPID_METHOD_REMOTEDESKTOPCLIENT_RETRIEVE_SETTINGS (723)

#define DISPID_METHOD_REMOTEDESKTOPCLIENT_SUSPEND_SCREEN_UPDATES (730)

#define DISPID_METHOD_REMOTEDESKTOPCLIENT_RESUME_SCREEN_UPDATES (731)

#define DISPID_METHOD_REMOTEDESKTOPCLIENT_EXECUTE_REMOTE_ACTION (732)

#define DISPID_METHOD_REMOTEDESKTOPCLIENT_GET_SNAPSHOT (733)

#define DISPID_PROP_REMOTEDESKTOPCLIENT_TOUCHPOINTER_ENABLED (740)

#define DISPID_PROP_REMOTEDESKTOPCLIENT_TOUCHPOINTER_EVENTSENABLED (741)

#define DISPID_PROP_REMOTEDESKTOPCLIENT_TOUCHPOINTER_POINTERSPEED (742)

#define DISPID_AX_CONNECTING (750)

#define DISPID_AX_CONNECTED (751)

#define DISPID_AX_LOGINCOMPLETED (752)

#define DISPID_AX_DISCONNECTED (753)

#define DISPID_AX_STATUSCHANGED (754)

#define DISPID_AX_AUTORECONNECTING (755)

#define DISPID_AX_AUTORECONNECTED (756)

#define DISPID_AX_DIALOGDISPLAYING (757)

#define DISPID_AX_DIALOGDISMISSED (758)

#define DISPID_AX_NETWORKSTATUSCHANGED (759)

#define DISPID_AX_ADMINMESSAGERECEIVED (760)

#define DISPID_AX_KEYCOMBINATIONPRESSED (761)

#define DISPID_AX_REMOTEDESKTOPSIZECHANGED (762)

#define DISPID_AX_TOUCHPOINTERCURSORMOVED (800)

/*****************************************************************************
 * IRemoteDesktopClientSettings interface
 */
#ifndef __IRemoteDesktopClientSettings_INTERFACE_DEFINED__
#define __IRemoteDesktopClientSettings_INTERFACE_DEFINED__

typedef enum __WIDL_rdpappcontainerclient_generated_name_0000001D {
    PasswordEncodingUTF8 = 0,
    PasswordEncodingUTF16LE = 1,
    PasswordEncodingUTF16BE = 2
} PasswordEncodingType;
DEFINE_GUID(IID_IRemoteDesktopClientSettings, 0x48a0f2a7, 0x2713, 0x431f, 0xbb,0xac, 0x6f,0x45,0x58,0xe7,0xd6,0x4d);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("48a0f2a7-2713-431f-bbac-6f4558e7d64d")
IRemoteDesktopClientSettings : public IDispatch
{
    virtual HRESULT STDMETHODCALLTYPE ApplySettings(
        BSTR rdpFileContents) = 0;

    virtual HRESULT STDMETHODCALLTYPE RetrieveSettings(
        BSTR *rdpFileContents) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetRdpProperty(
        BSTR propertyName,
        VARIANT *value) = 0;

    virtual HRESULT STDMETHODCALLTYPE SetRdpProperty(
        BSTR propertyName,
        VARIANT value) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IRemoteDesktopClientSettings, 0x48a0f2a7, 0x2713, 0x431f, 0xbb,0xac, 0x6f,0x45,0x58,0xe7,0xd6,0x4d)
#endif
#else
typedef struct IRemoteDesktopClientSettingsVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IRemoteDesktopClientSettings *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IRemoteDesktopClientSettings *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IRemoteDesktopClientSettings *This);

    /*** IDispatch methods ***/
    HRESULT (STDMETHODCALLTYPE *GetTypeInfoCount)(
        IRemoteDesktopClientSettings *This,
        UINT *pctinfo);

    HRESULT (STDMETHODCALLTYPE *GetTypeInfo)(
        IRemoteDesktopClientSettings *This,
        UINT iTInfo,
        LCID lcid,
        ITypeInfo **ppTInfo);

    HRESULT (STDMETHODCALLTYPE *GetIDsOfNames)(
        IRemoteDesktopClientSettings *This,
        REFIID riid,
        LPOLESTR *rgszNames,
        UINT cNames,
        LCID lcid,
        DISPID *rgDispId);

    HRESULT (STDMETHODCALLTYPE *Invoke)(
        IRemoteDesktopClientSettings *This,
        DISPID dispIdMember,
        REFIID riid,
        LCID lcid,
        WORD wFlags,
        DISPPARAMS *pDispParams,
        VARIANT *pVarResult,
        EXCEPINFO *pExcepInfo,
        UINT *puArgErr);

    /*** IRemoteDesktopClientSettings methods ***/
    HRESULT (STDMETHODCALLTYPE *ApplySettings)(
        IRemoteDesktopClientSettings *This,
        BSTR rdpFileContents);

    HRESULT (STDMETHODCALLTYPE *RetrieveSettings)(
        IRemoteDesktopClientSettings *This,
        BSTR *rdpFileContents);

    HRESULT (STDMETHODCALLTYPE *GetRdpProperty)(
        IRemoteDesktopClientSettings *This,
        BSTR propertyName,
        VARIANT *value);

    HRESULT (STDMETHODCALLTYPE *SetRdpProperty)(
        IRemoteDesktopClientSettings *This,
        BSTR propertyName,
        VARIANT value);

    END_INTERFACE
} IRemoteDesktopClientSettingsVtbl;

interface IRemoteDesktopClientSettings {
    CONST_VTBL IRemoteDesktopClientSettingsVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IRemoteDesktopClientSettings_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IRemoteDesktopClientSettings_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IRemoteDesktopClientSettings_Release(This) (This)->lpVtbl->Release(This)
/*** IDispatch methods ***/
#define IRemoteDesktopClientSettings_GetTypeInfoCount(This,pctinfo) (This)->lpVtbl->GetTypeInfoCount(This,pctinfo)
#define IRemoteDesktopClientSettings_GetTypeInfo(This,iTInfo,lcid,ppTInfo) (This)->lpVtbl->GetTypeInfo(This,iTInfo,lcid,ppTInfo)
#define IRemoteDesktopClientSettings_GetIDsOfNames(This,riid,rgszNames,cNames,lcid,rgDispId) (This)->lpVtbl->GetIDsOfNames(This,riid,rgszNames,cNames,lcid,rgDispId)
#define IRemoteDesktopClientSettings_Invoke(This,dispIdMember,riid,lcid,wFlags,pDispParams,pVarResult,pExcepInfo,puArgErr) (This)->lpVtbl->Invoke(This,dispIdMember,riid,lcid,wFlags,pDispParams,pVarResult,pExcepInfo,puArgErr)
/*** IRemoteDesktopClientSettings methods ***/
#define IRemoteDesktopClientSettings_ApplySettings(This,rdpFileContents) (This)->lpVtbl->ApplySettings(This,rdpFileContents)
#define IRemoteDesktopClientSettings_RetrieveSettings(This,rdpFileContents) (This)->lpVtbl->RetrieveSettings(This,rdpFileContents)
#define IRemoteDesktopClientSettings_GetRdpProperty(This,propertyName,value) (This)->lpVtbl->GetRdpProperty(This,propertyName,value)
#define IRemoteDesktopClientSettings_SetRdpProperty(This,propertyName,value) (This)->lpVtbl->SetRdpProperty(This,propertyName,value)
#else
/*** IUnknown methods ***/
static FORCEINLINE HRESULT IRemoteDesktopClientSettings_QueryInterface(IRemoteDesktopClientSettings* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static FORCEINLINE ULONG IRemoteDesktopClientSettings_AddRef(IRemoteDesktopClientSettings* This) {
    return This->lpVtbl->AddRef(This);
}
static FORCEINLINE ULONG IRemoteDesktopClientSettings_Release(IRemoteDesktopClientSettings* This) {
    return This->lpVtbl->Release(This);
}
/*** IDispatch methods ***/
static FORCEINLINE HRESULT IRemoteDesktopClientSettings_GetTypeInfoCount(IRemoteDesktopClientSettings* This,UINT *pctinfo) {
    return This->lpVtbl->GetTypeInfoCount(This,pctinfo);
}
static FORCEINLINE HRESULT IRemoteDesktopClientSettings_GetTypeInfo(IRemoteDesktopClientSettings* This,UINT iTInfo,LCID lcid,ITypeInfo **ppTInfo) {
    return This->lpVtbl->GetTypeInfo(This,iTInfo,lcid,ppTInfo);
}
static FORCEINLINE HRESULT IRemoteDesktopClientSettings_GetIDsOfNames(IRemoteDesktopClientSettings* This,REFIID riid,LPOLESTR *rgszNames,UINT cNames,LCID lcid,DISPID *rgDispId) {
    return This->lpVtbl->GetIDsOfNames(This,riid,rgszNames,cNames,lcid,rgDispId);
}
static FORCEINLINE HRESULT IRemoteDesktopClientSettings_Invoke(IRemoteDesktopClientSettings* This,DISPID dispIdMember,REFIID riid,LCID lcid,WORD wFlags,DISPPARAMS *pDispParams,VARIANT *pVarResult,EXCEPINFO *pExcepInfo,UINT *puArgErr) {
    return This->lpVtbl->Invoke(This,dispIdMember,riid,lcid,wFlags,pDispParams,pVarResult,pExcepInfo,puArgErr);
}
/*** IRemoteDesktopClientSettings methods ***/
static FORCEINLINE HRESULT IRemoteDesktopClientSettings_ApplySettings(IRemoteDesktopClientSettings* This,BSTR rdpFileContents) {
    return This->lpVtbl->ApplySettings(This,rdpFileContents);
}
static FORCEINLINE HRESULT IRemoteDesktopClientSettings_RetrieveSettings(IRemoteDesktopClientSettings* This,BSTR *rdpFileContents) {
    return This->lpVtbl->RetrieveSettings(This,rdpFileContents);
}
static FORCEINLINE HRESULT IRemoteDesktopClientSettings_GetRdpProperty(IRemoteDesktopClientSettings* This,BSTR propertyName,VARIANT *value) {
    return This->lpVtbl->GetRdpProperty(This,propertyName,value);
}
static FORCEINLINE HRESULT IRemoteDesktopClientSettings_SetRdpProperty(IRemoteDesktopClientSettings* This,BSTR propertyName,VARIANT value) {
    return This->lpVtbl->SetRdpProperty(This,propertyName,value);
}
#endif
#endif

#endif


#endif  /* __IRemoteDesktopClientSettings_INTERFACE_DEFINED__ */

/*****************************************************************************
 * IRemoteDesktopClientActions interface
 */
#ifndef __IRemoteDesktopClientActions_INTERFACE_DEFINED__
#define __IRemoteDesktopClientActions_INTERFACE_DEFINED__

typedef enum __WIDL_rdpappcontainerclient_generated_name_0000001E {
    RemoteActionCharms = 0,
    RemoteActionAppbar = 1,
    RemoteActionSnap = 2,
    RemoteActionStartScreen = 3,
    RemoteActionAppSwitch = 4
} RemoteActionType;
typedef enum __WIDL_rdpappcontainerclient_generated_name_0000001F {
    SnapshotEncodingDataUri = 0
} SnapshotEncodingType;
typedef enum __WIDL_rdpappcontainerclient_generated_name_00000020 {
    SnapshotFormatPng = 0,
    SnapshotFormatJpeg = 1,
    SnapshotFormatBmp = 2
} SnapshotFormatType;
DEFINE_GUID(IID_IRemoteDesktopClientActions, 0x7d54bc4e, 0x1028, 0x45d4, 0x8b,0x0a, 0xb9,0xb6,0xbf,0xfb,0xa1,0x76);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("7d54bc4e-1028-45d4-8b0a-b9b6bffba176")
IRemoteDesktopClientActions : public IDispatch
{
    virtual HRESULT STDMETHODCALLTYPE SuspendScreenUpdates(
        ) = 0;

    virtual HRESULT STDMETHODCALLTYPE ResumeScreenUpdates(
        ) = 0;

    virtual HRESULT STDMETHODCALLTYPE ExecuteRemoteAction(
        RemoteActionType remoteAction) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetSnapshot(
        SnapshotEncodingType snapshotEncoding,
        SnapshotFormatType snapshotFormat,
        ULONG snapshotWidth,
        ULONG snapshotHeight,
        BSTR *snapshotData) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IRemoteDesktopClientActions, 0x7d54bc4e, 0x1028, 0x45d4, 0x8b,0x0a, 0xb9,0xb6,0xbf,0xfb,0xa1,0x76)
#endif
#else
typedef struct IRemoteDesktopClientActionsVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IRemoteDesktopClientActions *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IRemoteDesktopClientActions *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IRemoteDesktopClientActions *This);

    /*** IDispatch methods ***/
    HRESULT (STDMETHODCALLTYPE *GetTypeInfoCount)(
        IRemoteDesktopClientActions *This,
        UINT *pctinfo);

    HRESULT (STDMETHODCALLTYPE *GetTypeInfo)(
        IRemoteDesktopClientActions *This,
        UINT iTInfo,
        LCID lcid,
        ITypeInfo **ppTInfo);

    HRESULT (STDMETHODCALLTYPE *GetIDsOfNames)(
        IRemoteDesktopClientActions *This,
        REFIID riid,
        LPOLESTR *rgszNames,
        UINT cNames,
        LCID lcid,
        DISPID *rgDispId);

    HRESULT (STDMETHODCALLTYPE *Invoke)(
        IRemoteDesktopClientActions *This,
        DISPID dispIdMember,
        REFIID riid,
        LCID lcid,
        WORD wFlags,
        DISPPARAMS *pDispParams,
        VARIANT *pVarResult,
        EXCEPINFO *pExcepInfo,
        UINT *puArgErr);

    /*** IRemoteDesktopClientActions methods ***/
    HRESULT (STDMETHODCALLTYPE *SuspendScreenUpdates)(
        IRemoteDesktopClientActions *This);

    HRESULT (STDMETHODCALLTYPE *ResumeScreenUpdates)(
        IRemoteDesktopClientActions *This);

    HRESULT (STDMETHODCALLTYPE *ExecuteRemoteAction)(
        IRemoteDesktopClientActions *This,
        RemoteActionType remoteAction);

    HRESULT (STDMETHODCALLTYPE *GetSnapshot)(
        IRemoteDesktopClientActions *This,
        SnapshotEncodingType snapshotEncoding,
        SnapshotFormatType snapshotFormat,
        ULONG snapshotWidth,
        ULONG snapshotHeight,
        BSTR *snapshotData);

    END_INTERFACE
} IRemoteDesktopClientActionsVtbl;

interface IRemoteDesktopClientActions {
    CONST_VTBL IRemoteDesktopClientActionsVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IRemoteDesktopClientActions_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IRemoteDesktopClientActions_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IRemoteDesktopClientActions_Release(This) (This)->lpVtbl->Release(This)
/*** IDispatch methods ***/
#define IRemoteDesktopClientActions_GetTypeInfoCount(This,pctinfo) (This)->lpVtbl->GetTypeInfoCount(This,pctinfo)
#define IRemoteDesktopClientActions_GetTypeInfo(This,iTInfo,lcid,ppTInfo) (This)->lpVtbl->GetTypeInfo(This,iTInfo,lcid,ppTInfo)
#define IRemoteDesktopClientActions_GetIDsOfNames(This,riid,rgszNames,cNames,lcid,rgDispId) (This)->lpVtbl->GetIDsOfNames(This,riid,rgszNames,cNames,lcid,rgDispId)
#define IRemoteDesktopClientActions_Invoke(This,dispIdMember,riid,lcid,wFlags,pDispParams,pVarResult,pExcepInfo,puArgErr) (This)->lpVtbl->Invoke(This,dispIdMember,riid,lcid,wFlags,pDispParams,pVarResult,pExcepInfo,puArgErr)
/*** IRemoteDesktopClientActions methods ***/
#define IRemoteDesktopClientActions_SuspendScreenUpdates(This) (This)->lpVtbl->SuspendScreenUpdates(This)
#define IRemoteDesktopClientActions_ResumeScreenUpdates(This) (This)->lpVtbl->ResumeScreenUpdates(This)
#define IRemoteDesktopClientActions_ExecuteRemoteAction(This,remoteAction) (This)->lpVtbl->ExecuteRemoteAction(This,remoteAction)
#define IRemoteDesktopClientActions_GetSnapshot(This,snapshotEncoding,snapshotFormat,snapshotWidth,snapshotHeight,snapshotData) (This)->lpVtbl->GetSnapshot(This,snapshotEncoding,snapshotFormat,snapshotWidth,snapshotHeight,snapshotData)
#else
/*** IUnknown methods ***/
static FORCEINLINE HRESULT IRemoteDesktopClientActions_QueryInterface(IRemoteDesktopClientActions* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static FORCEINLINE ULONG IRemoteDesktopClientActions_AddRef(IRemoteDesktopClientActions* This) {
    return This->lpVtbl->AddRef(This);
}
static FORCEINLINE ULONG IRemoteDesktopClientActions_Release(IRemoteDesktopClientActions* This) {
    return This->lpVtbl->Release(This);
}
/*** IDispatch methods ***/
static FORCEINLINE HRESULT IRemoteDesktopClientActions_GetTypeInfoCount(IRemoteDesktopClientActions* This,UINT *pctinfo) {
    return This->lpVtbl->GetTypeInfoCount(This,pctinfo);
}
static FORCEINLINE HRESULT IRemoteDesktopClientActions_GetTypeInfo(IRemoteDesktopClientActions* This,UINT iTInfo,LCID lcid,ITypeInfo **ppTInfo) {
    return This->lpVtbl->GetTypeInfo(This,iTInfo,lcid,ppTInfo);
}
static FORCEINLINE HRESULT IRemoteDesktopClientActions_GetIDsOfNames(IRemoteDesktopClientActions* This,REFIID riid,LPOLESTR *rgszNames,UINT cNames,LCID lcid,DISPID *rgDispId) {
    return This->lpVtbl->GetIDsOfNames(This,riid,rgszNames,cNames,lcid,rgDispId);
}
static FORCEINLINE HRESULT IRemoteDesktopClientActions_Invoke(IRemoteDesktopClientActions* This,DISPID dispIdMember,REFIID riid,LCID lcid,WORD wFlags,DISPPARAMS *pDispParams,VARIANT *pVarResult,EXCEPINFO *pExcepInfo,UINT *puArgErr) {
    return This->lpVtbl->Invoke(This,dispIdMember,riid,lcid,wFlags,pDispParams,pVarResult,pExcepInfo,puArgErr);
}
/*** IRemoteDesktopClientActions methods ***/
static FORCEINLINE HRESULT IRemoteDesktopClientActions_SuspendScreenUpdates(IRemoteDesktopClientActions* This) {
    return This->lpVtbl->SuspendScreenUpdates(This);
}
static FORCEINLINE HRESULT IRemoteDesktopClientActions_ResumeScreenUpdates(IRemoteDesktopClientActions* This) {
    return This->lpVtbl->ResumeScreenUpdates(This);
}
static FORCEINLINE HRESULT IRemoteDesktopClientActions_ExecuteRemoteAction(IRemoteDesktopClientActions* This,RemoteActionType remoteAction) {
    return This->lpVtbl->ExecuteRemoteAction(This,remoteAction);
}
static FORCEINLINE HRESULT IRemoteDesktopClientActions_GetSnapshot(IRemoteDesktopClientActions* This,SnapshotEncodingType snapshotEncoding,SnapshotFormatType snapshotFormat,ULONG snapshotWidth,ULONG snapshotHeight,BSTR *snapshotData) {
    return This->lpVtbl->GetSnapshot(This,snapshotEncoding,snapshotFormat,snapshotWidth,snapshotHeight,snapshotData);
}
#endif
#endif

#endif


#endif  /* __IRemoteDesktopClientActions_INTERFACE_DEFINED__ */

/*****************************************************************************
 * IRemoteDesktopClientTouchPointer interface
 */
#ifndef __IRemoteDesktopClientTouchPointer_INTERFACE_DEFINED__
#define __IRemoteDesktopClientTouchPointer_INTERFACE_DEFINED__

DEFINE_GUID(IID_IRemoteDesktopClientTouchPointer, 0x260ec22d, 0x8cbc, 0x44b5, 0x9e,0x88, 0x2a,0x37,0xf6,0xc9,0x3a,0xe9);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("260ec22d-8cbc-44b5-9e88-2a37f6c93ae9")
IRemoteDesktopClientTouchPointer : public IDispatch
{
    virtual HRESULT STDMETHODCALLTYPE put_Enabled(
        VARIANT_BOOL enabled) = 0;

    virtual HRESULT STDMETHODCALLTYPE get_Enabled(
        VARIANT_BOOL *enabled) = 0;

    virtual HRESULT STDMETHODCALLTYPE put_EventsEnabled(
        VARIANT_BOOL eventsEnabled) = 0;

    virtual HRESULT STDMETHODCALLTYPE get_EventsEnabled(
        VARIANT_BOOL *eventsEnabled) = 0;

    virtual HRESULT STDMETHODCALLTYPE put_PointerSpeed(
        ULONG pointerSpeed) = 0;

    virtual HRESULT STDMETHODCALLTYPE get_PointerSpeed(
        ULONG *pointerSpeed) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IRemoteDesktopClientTouchPointer, 0x260ec22d, 0x8cbc, 0x44b5, 0x9e,0x88, 0x2a,0x37,0xf6,0xc9,0x3a,0xe9)
#endif
#else
typedef struct IRemoteDesktopClientTouchPointerVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IRemoteDesktopClientTouchPointer *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IRemoteDesktopClientTouchPointer *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IRemoteDesktopClientTouchPointer *This);

    /*** IDispatch methods ***/
    HRESULT (STDMETHODCALLTYPE *GetTypeInfoCount)(
        IRemoteDesktopClientTouchPointer *This,
        UINT *pctinfo);

    HRESULT (STDMETHODCALLTYPE *GetTypeInfo)(
        IRemoteDesktopClientTouchPointer *This,
        UINT iTInfo,
        LCID lcid,
        ITypeInfo **ppTInfo);

    HRESULT (STDMETHODCALLTYPE *GetIDsOfNames)(
        IRemoteDesktopClientTouchPointer *This,
        REFIID riid,
        LPOLESTR *rgszNames,
        UINT cNames,
        LCID lcid,
        DISPID *rgDispId);

    HRESULT (STDMETHODCALLTYPE *Invoke)(
        IRemoteDesktopClientTouchPointer *This,
        DISPID dispIdMember,
        REFIID riid,
        LCID lcid,
        WORD wFlags,
        DISPPARAMS *pDispParams,
        VARIANT *pVarResult,
        EXCEPINFO *pExcepInfo,
        UINT *puArgErr);

    /*** IRemoteDesktopClientTouchPointer methods ***/
    HRESULT (STDMETHODCALLTYPE *put_Enabled)(
        IRemoteDesktopClientTouchPointer *This,
        VARIANT_BOOL enabled);

    HRESULT (STDMETHODCALLTYPE *get_Enabled)(
        IRemoteDesktopClientTouchPointer *This,
        VARIANT_BOOL *enabled);

    HRESULT (STDMETHODCALLTYPE *put_EventsEnabled)(
        IRemoteDesktopClientTouchPointer *This,
        VARIANT_BOOL eventsEnabled);

    HRESULT (STDMETHODCALLTYPE *get_EventsEnabled)(
        IRemoteDesktopClientTouchPointer *This,
        VARIANT_BOOL *eventsEnabled);

    HRESULT (STDMETHODCALLTYPE *put_PointerSpeed)(
        IRemoteDesktopClientTouchPointer *This,
        ULONG pointerSpeed);

    HRESULT (STDMETHODCALLTYPE *get_PointerSpeed)(
        IRemoteDesktopClientTouchPointer *This,
        ULONG *pointerSpeed);

    END_INTERFACE
} IRemoteDesktopClientTouchPointerVtbl;

interface IRemoteDesktopClientTouchPointer {
    CONST_VTBL IRemoteDesktopClientTouchPointerVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IRemoteDesktopClientTouchPointer_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IRemoteDesktopClientTouchPointer_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IRemoteDesktopClientTouchPointer_Release(This) (This)->lpVtbl->Release(This)
/*** IDispatch methods ***/
#define IRemoteDesktopClientTouchPointer_GetTypeInfoCount(This,pctinfo) (This)->lpVtbl->GetTypeInfoCount(This,pctinfo)
#define IRemoteDesktopClientTouchPointer_GetTypeInfo(This,iTInfo,lcid,ppTInfo) (This)->lpVtbl->GetTypeInfo(This,iTInfo,lcid,ppTInfo)
#define IRemoteDesktopClientTouchPointer_GetIDsOfNames(This,riid,rgszNames,cNames,lcid,rgDispId) (This)->lpVtbl->GetIDsOfNames(This,riid,rgszNames,cNames,lcid,rgDispId)
#define IRemoteDesktopClientTouchPointer_Invoke(This,dispIdMember,riid,lcid,wFlags,pDispParams,pVarResult,pExcepInfo,puArgErr) (This)->lpVtbl->Invoke(This,dispIdMember,riid,lcid,wFlags,pDispParams,pVarResult,pExcepInfo,puArgErr)
/*** IRemoteDesktopClientTouchPointer methods ***/
#define IRemoteDesktopClientTouchPointer_put_Enabled(This,enabled) (This)->lpVtbl->put_Enabled(This,enabled)
#define IRemoteDesktopClientTouchPointer_get_Enabled(This,enabled) (This)->lpVtbl->get_Enabled(This,enabled)
#define IRemoteDesktopClientTouchPointer_put_EventsEnabled(This,eventsEnabled) (This)->lpVtbl->put_EventsEnabled(This,eventsEnabled)
#define IRemoteDesktopClientTouchPointer_get_EventsEnabled(This,eventsEnabled) (This)->lpVtbl->get_EventsEnabled(This,eventsEnabled)
#define IRemoteDesktopClientTouchPointer_put_PointerSpeed(This,pointerSpeed) (This)->lpVtbl->put_PointerSpeed(This,pointerSpeed)
#define IRemoteDesktopClientTouchPointer_get_PointerSpeed(This,pointerSpeed) (This)->lpVtbl->get_PointerSpeed(This,pointerSpeed)
#else
/*** IUnknown methods ***/
static FORCEINLINE HRESULT IRemoteDesktopClientTouchPointer_QueryInterface(IRemoteDesktopClientTouchPointer* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static FORCEINLINE ULONG IRemoteDesktopClientTouchPointer_AddRef(IRemoteDesktopClientTouchPointer* This) {
    return This->lpVtbl->AddRef(This);
}
static FORCEINLINE ULONG IRemoteDesktopClientTouchPointer_Release(IRemoteDesktopClientTouchPointer* This) {
    return This->lpVtbl->Release(This);
}
/*** IDispatch methods ***/
static FORCEINLINE HRESULT IRemoteDesktopClientTouchPointer_GetTypeInfoCount(IRemoteDesktopClientTouchPointer* This,UINT *pctinfo) {
    return This->lpVtbl->GetTypeInfoCount(This,pctinfo);
}
static FORCEINLINE HRESULT IRemoteDesktopClientTouchPointer_GetTypeInfo(IRemoteDesktopClientTouchPointer* This,UINT iTInfo,LCID lcid,ITypeInfo **ppTInfo) {
    return This->lpVtbl->GetTypeInfo(This,iTInfo,lcid,ppTInfo);
}
static FORCEINLINE HRESULT IRemoteDesktopClientTouchPointer_GetIDsOfNames(IRemoteDesktopClientTouchPointer* This,REFIID riid,LPOLESTR *rgszNames,UINT cNames,LCID lcid,DISPID *rgDispId) {
    return This->lpVtbl->GetIDsOfNames(This,riid,rgszNames,cNames,lcid,rgDispId);
}
static FORCEINLINE HRESULT IRemoteDesktopClientTouchPointer_Invoke(IRemoteDesktopClientTouchPointer* This,DISPID dispIdMember,REFIID riid,LCID lcid,WORD wFlags,DISPPARAMS *pDispParams,VARIANT *pVarResult,EXCEPINFO *pExcepInfo,UINT *puArgErr) {
    return This->lpVtbl->Invoke(This,dispIdMember,riid,lcid,wFlags,pDispParams,pVarResult,pExcepInfo,puArgErr);
}
/*** IRemoteDesktopClientTouchPointer methods ***/
static FORCEINLINE HRESULT IRemoteDesktopClientTouchPointer_put_Enabled(IRemoteDesktopClientTouchPointer* This,VARIANT_BOOL enabled) {
    return This->lpVtbl->put_Enabled(This,enabled);
}
static FORCEINLINE HRESULT IRemoteDesktopClientTouchPointer_get_Enabled(IRemoteDesktopClientTouchPointer* This,VARIANT_BOOL *enabled) {
    return This->lpVtbl->get_Enabled(This,enabled);
}
static FORCEINLINE HRESULT IRemoteDesktopClientTouchPointer_put_EventsEnabled(IRemoteDesktopClientTouchPointer* This,VARIANT_BOOL eventsEnabled) {
    return This->lpVtbl->put_EventsEnabled(This,eventsEnabled);
}
static FORCEINLINE HRESULT IRemoteDesktopClientTouchPointer_get_EventsEnabled(IRemoteDesktopClientTouchPointer* This,VARIANT_BOOL *eventsEnabled) {
    return This->lpVtbl->get_EventsEnabled(This,eventsEnabled);
}
static FORCEINLINE HRESULT IRemoteDesktopClientTouchPointer_put_PointerSpeed(IRemoteDesktopClientTouchPointer* This,ULONG pointerSpeed) {
    return This->lpVtbl->put_PointerSpeed(This,pointerSpeed);
}
static FORCEINLINE HRESULT IRemoteDesktopClientTouchPointer_get_PointerSpeed(IRemoteDesktopClientTouchPointer* This,ULONG *pointerSpeed) {
    return This->lpVtbl->get_PointerSpeed(This,pointerSpeed);
}
#endif
#endif

#endif


#endif  /* __IRemoteDesktopClientTouchPointer_INTERFACE_DEFINED__ */

/*****************************************************************************
 * IRemoteDesktopClient interface
 */
#ifndef __IRemoteDesktopClient_INTERFACE_DEFINED__
#define __IRemoteDesktopClient_INTERFACE_DEFINED__

typedef enum __WIDL_rdpappcontainerclient_generated_name_00000021 {
    KeyCombinationHome = 0,
    KeyCombinationLeft = 1,
    KeyCombinationUp = 2,
    KeyCombinationRight = 3,
    KeyCombinationDown = 4,
    KeyCombinationScroll = 5
} KeyCombinationType;
DEFINE_GUID(IID_IRemoteDesktopClient, 0x57d25668, 0x625a, 0x4905, 0xbe,0x4e, 0x30,0x4c,0xaa,0x13,0xf8,0x9c);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("57d25668-625a-4905-be4e-304caa13f89c")
IRemoteDesktopClient : public IDispatch
{
    virtual HRESULT STDMETHODCALLTYPE Connect(
        ) = 0;

    virtual HRESULT STDMETHODCALLTYPE Disconnect(
        ) = 0;

    virtual HRESULT STDMETHODCALLTYPE Reconnect(
        ULONG width,
        ULONG height) = 0;

    virtual HRESULT STDMETHODCALLTYPE get_Settings(
        IRemoteDesktopClientSettings **settings) = 0;

    virtual HRESULT STDMETHODCALLTYPE get_Actions(
        IRemoteDesktopClientActions **actions) = 0;

    virtual HRESULT STDMETHODCALLTYPE get_TouchPointer(
        IRemoteDesktopClientTouchPointer **touchPointer) = 0;

    virtual HRESULT STDMETHODCALLTYPE DeleteSavedCredentials(
        BSTR serverName) = 0;

    virtual HRESULT STDMETHODCALLTYPE UpdateSessionDisplaySettings(
        ULONG width,
        ULONG height) = 0;

    virtual HRESULT STDMETHODCALLTYPE attachEvent(
        BSTR eventName,
        IDispatch *callback) = 0;

    virtual HRESULT STDMETHODCALLTYPE detachEvent(
        BSTR eventName,
        IDispatch *callback) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IRemoteDesktopClient, 0x57d25668, 0x625a, 0x4905, 0xbe,0x4e, 0x30,0x4c,0xaa,0x13,0xf8,0x9c)
#endif
#else
typedef struct IRemoteDesktopClientVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IRemoteDesktopClient *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IRemoteDesktopClient *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IRemoteDesktopClient *This);

    /*** IDispatch methods ***/
    HRESULT (STDMETHODCALLTYPE *GetTypeInfoCount)(
        IRemoteDesktopClient *This,
        UINT *pctinfo);

    HRESULT (STDMETHODCALLTYPE *GetTypeInfo)(
        IRemoteDesktopClient *This,
        UINT iTInfo,
        LCID lcid,
        ITypeInfo **ppTInfo);

    HRESULT (STDMETHODCALLTYPE *GetIDsOfNames)(
        IRemoteDesktopClient *This,
        REFIID riid,
        LPOLESTR *rgszNames,
        UINT cNames,
        LCID lcid,
        DISPID *rgDispId);

    HRESULT (STDMETHODCALLTYPE *Invoke)(
        IRemoteDesktopClient *This,
        DISPID dispIdMember,
        REFIID riid,
        LCID lcid,
        WORD wFlags,
        DISPPARAMS *pDispParams,
        VARIANT *pVarResult,
        EXCEPINFO *pExcepInfo,
        UINT *puArgErr);

    /*** IRemoteDesktopClient methods ***/
    HRESULT (STDMETHODCALLTYPE *Connect)(
        IRemoteDesktopClient *This);

    HRESULT (STDMETHODCALLTYPE *Disconnect)(
        IRemoteDesktopClient *This);

    HRESULT (STDMETHODCALLTYPE *Reconnect)(
        IRemoteDesktopClient *This,
        ULONG width,
        ULONG height);

    HRESULT (STDMETHODCALLTYPE *get_Settings)(
        IRemoteDesktopClient *This,
        IRemoteDesktopClientSettings **settings);

    HRESULT (STDMETHODCALLTYPE *get_Actions)(
        IRemoteDesktopClient *This,
        IRemoteDesktopClientActions **actions);

    HRESULT (STDMETHODCALLTYPE *get_TouchPointer)(
        IRemoteDesktopClient *This,
        IRemoteDesktopClientTouchPointer **touchPointer);

    HRESULT (STDMETHODCALLTYPE *DeleteSavedCredentials)(
        IRemoteDesktopClient *This,
        BSTR serverName);

    HRESULT (STDMETHODCALLTYPE *UpdateSessionDisplaySettings)(
        IRemoteDesktopClient *This,
        ULONG width,
        ULONG height);

    HRESULT (STDMETHODCALLTYPE *attachEvent)(
        IRemoteDesktopClient *This,
        BSTR eventName,
        IDispatch *callback);

    HRESULT (STDMETHODCALLTYPE *detachEvent)(
        IRemoteDesktopClient *This,
        BSTR eventName,
        IDispatch *callback);

    END_INTERFACE
} IRemoteDesktopClientVtbl;

interface IRemoteDesktopClient {
    CONST_VTBL IRemoteDesktopClientVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IRemoteDesktopClient_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IRemoteDesktopClient_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IRemoteDesktopClient_Release(This) (This)->lpVtbl->Release(This)
/*** IDispatch methods ***/
#define IRemoteDesktopClient_GetTypeInfoCount(This,pctinfo) (This)->lpVtbl->GetTypeInfoCount(This,pctinfo)
#define IRemoteDesktopClient_GetTypeInfo(This,iTInfo,lcid,ppTInfo) (This)->lpVtbl->GetTypeInfo(This,iTInfo,lcid,ppTInfo)
#define IRemoteDesktopClient_GetIDsOfNames(This,riid,rgszNames,cNames,lcid,rgDispId) (This)->lpVtbl->GetIDsOfNames(This,riid,rgszNames,cNames,lcid,rgDispId)
#define IRemoteDesktopClient_Invoke(This,dispIdMember,riid,lcid,wFlags,pDispParams,pVarResult,pExcepInfo,puArgErr) (This)->lpVtbl->Invoke(This,dispIdMember,riid,lcid,wFlags,pDispParams,pVarResult,pExcepInfo,puArgErr)
/*** IRemoteDesktopClient methods ***/
#define IRemoteDesktopClient_Connect(This) (This)->lpVtbl->Connect(This)
#define IRemoteDesktopClient_Disconnect(This) (This)->lpVtbl->Disconnect(This)
#define IRemoteDesktopClient_Reconnect(This,width,height) (This)->lpVtbl->Reconnect(This,width,height)
#define IRemoteDesktopClient_get_Settings(This,settings) (This)->lpVtbl->get_Settings(This,settings)
#define IRemoteDesktopClient_get_Actions(This,actions) (This)->lpVtbl->get_Actions(This,actions)
#define IRemoteDesktopClient_get_TouchPointer(This,touchPointer) (This)->lpVtbl->get_TouchPointer(This,touchPointer)
#define IRemoteDesktopClient_DeleteSavedCredentials(This,serverName) (This)->lpVtbl->DeleteSavedCredentials(This,serverName)
#define IRemoteDesktopClient_UpdateSessionDisplaySettings(This,width,height) (This)->lpVtbl->UpdateSessionDisplaySettings(This,width,height)
#define IRemoteDesktopClient_attachEvent(This,eventName,callback) (This)->lpVtbl->attachEvent(This,eventName,callback)
#define IRemoteDesktopClient_detachEvent(This,eventName,callback) (This)->lpVtbl->detachEvent(This,eventName,callback)
#else
/*** IUnknown methods ***/
static FORCEINLINE HRESULT IRemoteDesktopClient_QueryInterface(IRemoteDesktopClient* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static FORCEINLINE ULONG IRemoteDesktopClient_AddRef(IRemoteDesktopClient* This) {
    return This->lpVtbl->AddRef(This);
}
static FORCEINLINE ULONG IRemoteDesktopClient_Release(IRemoteDesktopClient* This) {
    return This->lpVtbl->Release(This);
}
/*** IDispatch methods ***/
static FORCEINLINE HRESULT IRemoteDesktopClient_GetTypeInfoCount(IRemoteDesktopClient* This,UINT *pctinfo) {
    return This->lpVtbl->GetTypeInfoCount(This,pctinfo);
}
static FORCEINLINE HRESULT IRemoteDesktopClient_GetTypeInfo(IRemoteDesktopClient* This,UINT iTInfo,LCID lcid,ITypeInfo **ppTInfo) {
    return This->lpVtbl->GetTypeInfo(This,iTInfo,lcid,ppTInfo);
}
static FORCEINLINE HRESULT IRemoteDesktopClient_GetIDsOfNames(IRemoteDesktopClient* This,REFIID riid,LPOLESTR *rgszNames,UINT cNames,LCID lcid,DISPID *rgDispId) {
    return This->lpVtbl->GetIDsOfNames(This,riid,rgszNames,cNames,lcid,rgDispId);
}
static FORCEINLINE HRESULT IRemoteDesktopClient_Invoke(IRemoteDesktopClient* This,DISPID dispIdMember,REFIID riid,LCID lcid,WORD wFlags,DISPPARAMS *pDispParams,VARIANT *pVarResult,EXCEPINFO *pExcepInfo,UINT *puArgErr) {
    return This->lpVtbl->Invoke(This,dispIdMember,riid,lcid,wFlags,pDispParams,pVarResult,pExcepInfo,puArgErr);
}
/*** IRemoteDesktopClient methods ***/
static FORCEINLINE HRESULT IRemoteDesktopClient_Connect(IRemoteDesktopClient* This) {
    return This->lpVtbl->Connect(This);
}
static FORCEINLINE HRESULT IRemoteDesktopClient_Disconnect(IRemoteDesktopClient* This) {
    return This->lpVtbl->Disconnect(This);
}
static FORCEINLINE HRESULT IRemoteDesktopClient_Reconnect(IRemoteDesktopClient* This,ULONG width,ULONG height) {
    return This->lpVtbl->Reconnect(This,width,height);
}
static FORCEINLINE HRESULT IRemoteDesktopClient_get_Settings(IRemoteDesktopClient* This,IRemoteDesktopClientSettings **settings) {
    return This->lpVtbl->get_Settings(This,settings);
}
static FORCEINLINE HRESULT IRemoteDesktopClient_get_Actions(IRemoteDesktopClient* This,IRemoteDesktopClientActions **actions) {
    return This->lpVtbl->get_Actions(This,actions);
}
static FORCEINLINE HRESULT IRemoteDesktopClient_get_TouchPointer(IRemoteDesktopClient* This,IRemoteDesktopClientTouchPointer **touchPointer) {
    return This->lpVtbl->get_TouchPointer(This,touchPointer);
}
static FORCEINLINE HRESULT IRemoteDesktopClient_DeleteSavedCredentials(IRemoteDesktopClient* This,BSTR serverName) {
    return This->lpVtbl->DeleteSavedCredentials(This,serverName);
}
static FORCEINLINE HRESULT IRemoteDesktopClient_UpdateSessionDisplaySettings(IRemoteDesktopClient* This,ULONG width,ULONG height) {
    return This->lpVtbl->UpdateSessionDisplaySettings(This,width,height);
}
static FORCEINLINE HRESULT IRemoteDesktopClient_attachEvent(IRemoteDesktopClient* This,BSTR eventName,IDispatch *callback) {
    return This->lpVtbl->attachEvent(This,eventName,callback);
}
static FORCEINLINE HRESULT IRemoteDesktopClient_detachEvent(IRemoteDesktopClient* This,BSTR eventName,IDispatch *callback) {
    return This->lpVtbl->detachEvent(This,eventName,callback);
}
#endif
#endif

#endif


#endif  /* __IRemoteDesktopClient_INTERFACE_DEFINED__ */

#endif
/* Begin additional prototypes for all interfaces */

ULONG           __RPC_USER BSTR_UserSize     (ULONG *, ULONG, BSTR *);
unsigned char * __RPC_USER BSTR_UserMarshal  (ULONG *, unsigned char *, BSTR *);
unsigned char * __RPC_USER BSTR_UserUnmarshal(ULONG *, unsigned char *, BSTR *);
void            __RPC_USER BSTR_UserFree     (ULONG *, BSTR *);
ULONG           __RPC_USER VARIANT_UserSize     (ULONG *, ULONG, VARIANT *);
unsigned char * __RPC_USER VARIANT_UserMarshal  (ULONG *, unsigned char *, VARIANT *);
unsigned char * __RPC_USER VARIANT_UserUnmarshal(ULONG *, unsigned char *, VARIANT *);
void            __RPC_USER VARIANT_UserFree     (ULONG *, VARIANT *);

/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __rdpappcontainerclient_h__ */
