/*** Autogenerated by WIDL 5.0 from ./amsi.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __amsi_h__
#define __amsi_h__

/* Forward declarations */

#ifndef __IAmsiStream_FWD_DEFINED__
#define __IAmsiStream_FWD_DEFINED__
typedef interface IAmsiStream IAmsiStream;
#ifdef __cplusplus
interface IAmsiStream;
#endif /* __cplusplus */
#endif

#ifndef __IAntimalwareProvider_FWD_DEFINED__
#define __IAntimalwareProvider_FWD_DEFINED__
typedef interface IAntimalwareProvider IAntimalwareProvider;
#ifdef __cplusplus
interface IAntimalwareProvider;
#endif /* __cplusplus */
#endif

#ifndef __IAntimalwareUacProvider_FWD_DEFINED__
#define __IAntimalwareUacProvider_FWD_DEFINED__
typedef interface IAntimalwareUacProvider IAntimalwareUacProvider;
#ifdef __cplusplus
interface IAntimalwareUacProvider;
#endif /* __cplusplus */
#endif

#ifndef __IAntimalwareProvider2_FWD_DEFINED__
#define __IAntimalwareProvider2_FWD_DEFINED__
typedef interface IAntimalwareProvider2 IAntimalwareProvider2;
#ifdef __cplusplus
interface IAntimalwareProvider2;
#endif /* __cplusplus */
#endif

#ifndef __IAntimalware_FWD_DEFINED__
#define __IAntimalware_FWD_DEFINED__
typedef interface IAntimalware IAntimalware;
#ifdef __cplusplus
interface IAntimalware;
#endif /* __cplusplus */
#endif

#ifndef __IAntimalware2_FWD_DEFINED__
#define __IAntimalware2_FWD_DEFINED__
typedef interface IAntimalware2 IAntimalware2;
#ifdef __cplusplus
interface IAntimalware2;
#endif /* __cplusplus */
#endif

/* Headers for imported files */

#include <oaidl.h>
#include <ocidl.h>

#ifdef __cplusplus
extern "C" {
#endif

#include <winapifamily.h>

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP)
typedef enum AMSI_RESULT {
    AMSI_RESULT_CLEAN = 0,
    AMSI_RESULT_NOT_DETECTED = 1,
    AMSI_RESULT_BLOCKED_BY_ADMIN_START = 0x4000,
    AMSI_RESULT_BLOCKED_BY_ADMIN_END = 0x4fff,
    AMSI_RESULT_DETECTED = 32768
} AMSI_RESULT;
#define AmsiResultIsMalware(r) ((r) >= AMSI_RESULT_DETECTED)
#define AmsiResultIsBlockedByAdmin(r) ((r) >= AMSI_RESULT_BLOCKED_BY_ADMIN_START) && (r) <= AMSI_RESULT_BLOCKED_BY_ADMIN_END
typedef enum AMSI_ATTRIBUTE {
    AMSI_ATTRIBUTE_APP_NAME = 0,
    AMSI_ATTRIBUTE_CONTENT_NAME = 1,
    AMSI_ATTRIBUTE_CONTENT_SIZE = 2,
    AMSI_ATTRIBUTE_CONTENT_ADDRESS = 3,
    AMSI_ATTRIBUTE_SESSION = 4,
    AMSI_ATTRIBUTE_REDIRECT_CHAIN_SIZE = 5,
    AMSI_ATTRIBUTE_REDIRECT_CHAIN_ADDRESS = 6,
    AMSI_ATTRIBUTE_ALL_SIZE = 7,
    AMSI_ATTRIBUTE_ALL_ADDRESS = 8,
    AMSI_ATTRIBUTE_QUIET = 9
} AMSI_ATTRIBUTE;
typedef enum AMSI_UAC_REQUEST_TYPE {
    AMSI_UAC_REQUEST_TYPE_EXE = 0,
    AMSI_UAC_REQUEST_TYPE_COM = 1,
    AMSI_UAC_REQUEST_TYPE_MSI = 2,
    AMSI_UAC_REQUEST_TYPE_AX = 3,
    AMSI_UAC_REQUEST_TYPE_PACKAGED_APP = 4,
    AMSI_UAC_REQUEST_TYPE_MAX = 5
} AMSI_UAC_REQUEST_TYPE;
typedef enum AMSI_UAC_TRUST_STATE {
    AMSI_UAC_TRUST_STATE_TRUSTED = 0,
    AMSI_UAC_TRUST_STATE_UNTRUSTED = 1,
    AMSI_UAC_TRUST_STATE_BLOCKED = 2,
    AMSI_UAC_TRUST_STATE_MAX = 3
} AMSI_UAC_TRUST_STATE;
typedef enum AMSI_UAC_MSI_ACTION {
    AMSI_UAC_MSI_ACTION_INSTALL = 0,
    AMSI_UAC_MSI_ACTION_UNINSTALL = 1,
    AMSI_UAC_MSI_ACTION_UPDATE = 2,
    AMSI_UAC_MSI_ACTION_MAINTENANCE = 3,
    AMSI_UAC_MSI_ACTION_MAX = 4
} AMSI_UAC_MSI_ACTION;
typedef struct AMSI_UAC_REQUEST_EXE_INFO {
    ULONG ulLength;
    LPWSTR lpwszApplicationName;
    LPWSTR lpwszCommandLine;
    LPWSTR lpwszDLLParameter;
} AMSI_UAC_REQUEST_EXE_INFO;
typedef struct AMSI_UAC_REQUEST_EXE_INFO *LPAMSI_UAC_REQUEST_EXE_INFO;
typedef struct AMSI_UAC_REQUEST_COM_INFO {
    ULONG ulLength;
    LPWSTR lpwszServerBinary;
    LPWSTR lpwszRequestor;
    GUID Clsid;
} AMSI_UAC_REQUEST_COM_INFO;
typedef struct AMSI_UAC_REQUEST_COM_INFO *LPAMSI_UAC_REQUEST_COM_INFO;
typedef struct AMSI_UAC_REQUEST_MSI_INFO {
    ULONG ulLength;
    AMSI_UAC_MSI_ACTION MsiAction;
    LPWSTR lpwszProductName;
    LPWSTR lpwszVersion;
    LPWSTR lpwszLanguage;
    LPWSTR lpwszManufacturer;
    LPWSTR lpwszPackagePath;
    LPWSTR lpwszPackageSource;
    ULONG ulUpdates;
    LPWSTR *ppwszUpdates;
    LPWSTR *ppwszUpdateSources;
} AMSI_UAC_REQUEST_MSI_INFO;
typedef struct AMSI_UAC_REQUEST_MSI_INFO *LPAMSI_UAC_REQUEST_MSI_INFO;
typedef struct AMSI_UAC_REQUEST_AX_INFO {
    ULONG ulLength;
    LPWSTR lpwszLocalInstallPath;
    LPWSTR lpwszSourceURL;
} AMSI_UAC_REQUEST_AX_INFO;
typedef struct AMSI_UAC_REQUEST_AX_INFO *LPAMSI_UAC_REQUEST_AX_INFO;
typedef struct AMSI_UAC_REQUEST_PACKAGED_APP_INFO {
    ULONG ulLength;
    LPWSTR lpwszApplicationName;
    LPWSTR lpwszCommandLine;
    LPWSTR lpPackageFamilyName;
    LPWSTR lpApplicationId;
} AMSI_UAC_REQUEST_PACKAGED_APP_INFO;
typedef struct AMSI_UAC_REQUEST_PACKAGED_APP_INFO *LPAMSI_UAC_REQUEST_PACKAGED_APP_INFO;
typedef struct AMSI_UAC_REQUEST_CONTEXT {
    ULONG ulLength;
    ULONG ulRequestorProcessId;
    AMSI_UAC_TRUST_STATE UACTrustState;
    AMSI_UAC_REQUEST_TYPE Type;
    union {
        AMSI_UAC_REQUEST_EXE_INFO ExeInfo;
        AMSI_UAC_REQUEST_COM_INFO ComInfo;
        AMSI_UAC_REQUEST_MSI_INFO MsiInfo;
        AMSI_UAC_REQUEST_AX_INFO ActiveXInfo;
        AMSI_UAC_REQUEST_PACKAGED_APP_INFO PackagedAppInfo;
    } RequestType;
    BOOL bAutoElevateRequest;
} AMSI_UAC_REQUEST_CONTEXT;
typedef struct AMSI_UAC_REQUEST_CONTEXT *LPAMSI_UAC_REQUEST_CONTEXT;
/*****************************************************************************
 * IAmsiStream interface
 */
#ifndef __IAmsiStream_INTERFACE_DEFINED__
#define __IAmsiStream_INTERFACE_DEFINED__

DEFINE_GUID(IID_IAmsiStream, 0x3e47f2e5, 0x81d4, 0x4d3b, 0x89,0x7f, 0x54,0x50,0x96,0x77,0x03,0x73);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("3e47f2e5-81d4-4d3b-897f-545096770373")
IAmsiStream : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE GetAttribute(
        AMSI_ATTRIBUTE attribute,
        ULONG dataSize,
        unsigned char *data,
        ULONG *retData) = 0;

    virtual HRESULT STDMETHODCALLTYPE Read(
        ULONGLONG position,
        ULONG size,
        unsigned char *buffer,
        ULONG *readSize) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IAmsiStream, 0x3e47f2e5, 0x81d4, 0x4d3b, 0x89,0x7f, 0x54,0x50,0x96,0x77,0x03,0x73)
#endif
#else
typedef struct IAmsiStreamVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IAmsiStream *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IAmsiStream *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IAmsiStream *This);

    /*** IAmsiStream methods ***/
    HRESULT (STDMETHODCALLTYPE *GetAttribute)(
        IAmsiStream *This,
        AMSI_ATTRIBUTE attribute,
        ULONG dataSize,
        unsigned char *data,
        ULONG *retData);

    HRESULT (STDMETHODCALLTYPE *Read)(
        IAmsiStream *This,
        ULONGLONG position,
        ULONG size,
        unsigned char *buffer,
        ULONG *readSize);

    END_INTERFACE
} IAmsiStreamVtbl;

interface IAmsiStream {
    CONST_VTBL IAmsiStreamVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IAmsiStream_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IAmsiStream_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IAmsiStream_Release(This) (This)->lpVtbl->Release(This)
/*** IAmsiStream methods ***/
#define IAmsiStream_GetAttribute(This,attribute,dataSize,data,retData) (This)->lpVtbl->GetAttribute(This,attribute,dataSize,data,retData)
#define IAmsiStream_Read(This,position,size,buffer,readSize) (This)->lpVtbl->Read(This,position,size,buffer,readSize)
#else
/*** IUnknown methods ***/
static FORCEINLINE HRESULT IAmsiStream_QueryInterface(IAmsiStream* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static FORCEINLINE ULONG IAmsiStream_AddRef(IAmsiStream* This) {
    return This->lpVtbl->AddRef(This);
}
static FORCEINLINE ULONG IAmsiStream_Release(IAmsiStream* This) {
    return This->lpVtbl->Release(This);
}
/*** IAmsiStream methods ***/
static FORCEINLINE HRESULT IAmsiStream_GetAttribute(IAmsiStream* This,AMSI_ATTRIBUTE attribute,ULONG dataSize,unsigned char *data,ULONG *retData) {
    return This->lpVtbl->GetAttribute(This,attribute,dataSize,data,retData);
}
static FORCEINLINE HRESULT IAmsiStream_Read(IAmsiStream* This,ULONGLONG position,ULONG size,unsigned char *buffer,ULONG *readSize) {
    return This->lpVtbl->Read(This,position,size,buffer,readSize);
}
#endif
#endif

#endif


#endif  /* __IAmsiStream_INTERFACE_DEFINED__ */

/*****************************************************************************
 * IAntimalwareProvider interface
 */
#ifndef __IAntimalwareProvider_INTERFACE_DEFINED__
#define __IAntimalwareProvider_INTERFACE_DEFINED__

DEFINE_GUID(IID_IAntimalwareProvider, 0xb2cabfe3, 0xfe04, 0x42b1, 0xa5,0xdf, 0x08,0xd4,0x83,0xd4,0xd1,0x25);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("b2cabfe3-fe04-42b1-a5df-08d483d4d125")
IAntimalwareProvider : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE Scan(
        IAmsiStream *stream,
        AMSI_RESULT *result) = 0;

    virtual void STDMETHODCALLTYPE CloseSession(
        ULONGLONG session) = 0;

    virtual HRESULT STDMETHODCALLTYPE DisplayName(
        LPWSTR *displayName) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IAntimalwareProvider, 0xb2cabfe3, 0xfe04, 0x42b1, 0xa5,0xdf, 0x08,0xd4,0x83,0xd4,0xd1,0x25)
#endif
#else
typedef struct IAntimalwareProviderVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IAntimalwareProvider *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IAntimalwareProvider *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IAntimalwareProvider *This);

    /*** IAntimalwareProvider methods ***/
    HRESULT (STDMETHODCALLTYPE *Scan)(
        IAntimalwareProvider *This,
        IAmsiStream *stream,
        AMSI_RESULT *result);

    void (STDMETHODCALLTYPE *CloseSession)(
        IAntimalwareProvider *This,
        ULONGLONG session);

    HRESULT (STDMETHODCALLTYPE *DisplayName)(
        IAntimalwareProvider *This,
        LPWSTR *displayName);

    END_INTERFACE
} IAntimalwareProviderVtbl;

interface IAntimalwareProvider {
    CONST_VTBL IAntimalwareProviderVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IAntimalwareProvider_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IAntimalwareProvider_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IAntimalwareProvider_Release(This) (This)->lpVtbl->Release(This)
/*** IAntimalwareProvider methods ***/
#define IAntimalwareProvider_Scan(This,stream,result) (This)->lpVtbl->Scan(This,stream,result)
#define IAntimalwareProvider_CloseSession(This,session) (This)->lpVtbl->CloseSession(This,session)
#define IAntimalwareProvider_DisplayName(This,displayName) (This)->lpVtbl->DisplayName(This,displayName)
#else
/*** IUnknown methods ***/
static FORCEINLINE HRESULT IAntimalwareProvider_QueryInterface(IAntimalwareProvider* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static FORCEINLINE ULONG IAntimalwareProvider_AddRef(IAntimalwareProvider* This) {
    return This->lpVtbl->AddRef(This);
}
static FORCEINLINE ULONG IAntimalwareProvider_Release(IAntimalwareProvider* This) {
    return This->lpVtbl->Release(This);
}
/*** IAntimalwareProvider methods ***/
static FORCEINLINE HRESULT IAntimalwareProvider_Scan(IAntimalwareProvider* This,IAmsiStream *stream,AMSI_RESULT *result) {
    return This->lpVtbl->Scan(This,stream,result);
}
static FORCEINLINE void IAntimalwareProvider_CloseSession(IAntimalwareProvider* This,ULONGLONG session) {
    This->lpVtbl->CloseSession(This,session);
}
static FORCEINLINE HRESULT IAntimalwareProvider_DisplayName(IAntimalwareProvider* This,LPWSTR *displayName) {
    return This->lpVtbl->DisplayName(This,displayName);
}
#endif
#endif

#endif


#endif  /* __IAntimalwareProvider_INTERFACE_DEFINED__ */

/*****************************************************************************
 * IAntimalwareUacProvider interface
 */
#ifndef __IAntimalwareUacProvider_INTERFACE_DEFINED__
#define __IAntimalwareUacProvider_INTERFACE_DEFINED__

DEFINE_GUID(IID_IAntimalwareUacProvider, 0xb2cabfe4, 0xfe04, 0x42b1, 0xa5,0xdf, 0x08,0xd4,0x83,0xd4,0xd1,0x25);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("b2cabfe4-fe04-42b1-a5df-08d483d4d125")
IAntimalwareUacProvider : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE UacScan(
        LPAMSI_UAC_REQUEST_CONTEXT context,
        AMSI_RESULT *result) = 0;

    virtual HRESULT STDMETHODCALLTYPE DisplayName(
        LPWSTR *displayName) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IAntimalwareUacProvider, 0xb2cabfe4, 0xfe04, 0x42b1, 0xa5,0xdf, 0x08,0xd4,0x83,0xd4,0xd1,0x25)
#endif
#else
typedef struct IAntimalwareUacProviderVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IAntimalwareUacProvider *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IAntimalwareUacProvider *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IAntimalwareUacProvider *This);

    /*** IAntimalwareUacProvider methods ***/
    HRESULT (STDMETHODCALLTYPE *UacScan)(
        IAntimalwareUacProvider *This,
        LPAMSI_UAC_REQUEST_CONTEXT context,
        AMSI_RESULT *result);

    HRESULT (STDMETHODCALLTYPE *DisplayName)(
        IAntimalwareUacProvider *This,
        LPWSTR *displayName);

    END_INTERFACE
} IAntimalwareUacProviderVtbl;

interface IAntimalwareUacProvider {
    CONST_VTBL IAntimalwareUacProviderVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IAntimalwareUacProvider_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IAntimalwareUacProvider_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IAntimalwareUacProvider_Release(This) (This)->lpVtbl->Release(This)
/*** IAntimalwareUacProvider methods ***/
#define IAntimalwareUacProvider_UacScan(This,context,result) (This)->lpVtbl->UacScan(This,context,result)
#define IAntimalwareUacProvider_DisplayName(This,displayName) (This)->lpVtbl->DisplayName(This,displayName)
#else
/*** IUnknown methods ***/
static FORCEINLINE HRESULT IAntimalwareUacProvider_QueryInterface(IAntimalwareUacProvider* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static FORCEINLINE ULONG IAntimalwareUacProvider_AddRef(IAntimalwareUacProvider* This) {
    return This->lpVtbl->AddRef(This);
}
static FORCEINLINE ULONG IAntimalwareUacProvider_Release(IAntimalwareUacProvider* This) {
    return This->lpVtbl->Release(This);
}
/*** IAntimalwareUacProvider methods ***/
static FORCEINLINE HRESULT IAntimalwareUacProvider_UacScan(IAntimalwareUacProvider* This,LPAMSI_UAC_REQUEST_CONTEXT context,AMSI_RESULT *result) {
    return This->lpVtbl->UacScan(This,context,result);
}
static FORCEINLINE HRESULT IAntimalwareUacProvider_DisplayName(IAntimalwareUacProvider* This,LPWSTR *displayName) {
    return This->lpVtbl->DisplayName(This,displayName);
}
#endif
#endif

#endif


#endif  /* __IAntimalwareUacProvider_INTERFACE_DEFINED__ */

/*****************************************************************************
 * IAntimalwareProvider2 interface
 */
#ifndef __IAntimalwareProvider2_INTERFACE_DEFINED__
#define __IAntimalwareProvider2_INTERFACE_DEFINED__

DEFINE_GUID(IID_IAntimalwareProvider2, 0x7c1e6570, 0x3f73, 0x4e0f, 0x8a,0xd4, 0x98,0xb9,0x4c,0xd3,0x29,0x0f);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("7c1e6570-3f73-4e0f-8ad4-98b94cd3290f")
IAntimalwareProvider2 : public IAntimalwareProvider
{
    virtual HRESULT STDMETHODCALLTYPE Notify(
        PVOID buffer,
        ULONG length,
        LPCWSTR contentName,
        LPCWSTR appName,
        AMSI_RESULT *pResult) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IAntimalwareProvider2, 0x7c1e6570, 0x3f73, 0x4e0f, 0x8a,0xd4, 0x98,0xb9,0x4c,0xd3,0x29,0x0f)
#endif
#else
typedef struct IAntimalwareProvider2Vtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IAntimalwareProvider2 *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IAntimalwareProvider2 *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IAntimalwareProvider2 *This);

    /*** IAntimalwareProvider methods ***/
    HRESULT (STDMETHODCALLTYPE *Scan)(
        IAntimalwareProvider2 *This,
        IAmsiStream *stream,
        AMSI_RESULT *result);

    void (STDMETHODCALLTYPE *CloseSession)(
        IAntimalwareProvider2 *This,
        ULONGLONG session);

    HRESULT (STDMETHODCALLTYPE *DisplayName)(
        IAntimalwareProvider2 *This,
        LPWSTR *displayName);

    /*** IAntimalwareProvider2 methods ***/
    HRESULT (STDMETHODCALLTYPE *Notify)(
        IAntimalwareProvider2 *This,
        PVOID buffer,
        ULONG length,
        LPCWSTR contentName,
        LPCWSTR appName,
        AMSI_RESULT *pResult);

    END_INTERFACE
} IAntimalwareProvider2Vtbl;

interface IAntimalwareProvider2 {
    CONST_VTBL IAntimalwareProvider2Vtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IAntimalwareProvider2_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IAntimalwareProvider2_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IAntimalwareProvider2_Release(This) (This)->lpVtbl->Release(This)
/*** IAntimalwareProvider methods ***/
#define IAntimalwareProvider2_Scan(This,stream,result) (This)->lpVtbl->Scan(This,stream,result)
#define IAntimalwareProvider2_CloseSession(This,session) (This)->lpVtbl->CloseSession(This,session)
#define IAntimalwareProvider2_DisplayName(This,displayName) (This)->lpVtbl->DisplayName(This,displayName)
/*** IAntimalwareProvider2 methods ***/
#define IAntimalwareProvider2_Notify(This,buffer,length,contentName,appName,pResult) (This)->lpVtbl->Notify(This,buffer,length,contentName,appName,pResult)
#else
/*** IUnknown methods ***/
static FORCEINLINE HRESULT IAntimalwareProvider2_QueryInterface(IAntimalwareProvider2* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static FORCEINLINE ULONG IAntimalwareProvider2_AddRef(IAntimalwareProvider2* This) {
    return This->lpVtbl->AddRef(This);
}
static FORCEINLINE ULONG IAntimalwareProvider2_Release(IAntimalwareProvider2* This) {
    return This->lpVtbl->Release(This);
}
/*** IAntimalwareProvider methods ***/
static FORCEINLINE HRESULT IAntimalwareProvider2_Scan(IAntimalwareProvider2* This,IAmsiStream *stream,AMSI_RESULT *result) {
    return This->lpVtbl->Scan(This,stream,result);
}
static FORCEINLINE void IAntimalwareProvider2_CloseSession(IAntimalwareProvider2* This,ULONGLONG session) {
    This->lpVtbl->CloseSession(This,session);
}
static FORCEINLINE HRESULT IAntimalwareProvider2_DisplayName(IAntimalwareProvider2* This,LPWSTR *displayName) {
    return This->lpVtbl->DisplayName(This,displayName);
}
/*** IAntimalwareProvider2 methods ***/
static FORCEINLINE HRESULT IAntimalwareProvider2_Notify(IAntimalwareProvider2* This,PVOID buffer,ULONG length,LPCWSTR contentName,LPCWSTR appName,AMSI_RESULT *pResult) {
    return This->lpVtbl->Notify(This,buffer,length,contentName,appName,pResult);
}
#endif
#endif

#endif


#endif  /* __IAntimalwareProvider2_INTERFACE_DEFINED__ */

/*****************************************************************************
 * IAntimalware interface
 */
#ifndef __IAntimalware_INTERFACE_DEFINED__
#define __IAntimalware_INTERFACE_DEFINED__

DEFINE_GUID(IID_IAntimalware, 0x82d29c2e, 0xf062, 0x44e6, 0xb5,0xc9, 0x3d,0x9a,0x2f,0x24,0xa2,0xdf);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("82d29c2e-f062-44e6-b5c9-3d9a2f24a2df")
IAntimalware : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE Scan(
        IAmsiStream *stream,
        AMSI_RESULT *result,
        IAntimalwareProvider **provider) = 0;

    virtual void STDMETHODCALLTYPE CloseSession(
        ULONGLONG session) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IAntimalware, 0x82d29c2e, 0xf062, 0x44e6, 0xb5,0xc9, 0x3d,0x9a,0x2f,0x24,0xa2,0xdf)
#endif
#else
typedef struct IAntimalwareVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IAntimalware *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IAntimalware *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IAntimalware *This);

    /*** IAntimalware methods ***/
    HRESULT (STDMETHODCALLTYPE *Scan)(
        IAntimalware *This,
        IAmsiStream *stream,
        AMSI_RESULT *result,
        IAntimalwareProvider **provider);

    void (STDMETHODCALLTYPE *CloseSession)(
        IAntimalware *This,
        ULONGLONG session);

    END_INTERFACE
} IAntimalwareVtbl;

interface IAntimalware {
    CONST_VTBL IAntimalwareVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IAntimalware_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IAntimalware_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IAntimalware_Release(This) (This)->lpVtbl->Release(This)
/*** IAntimalware methods ***/
#define IAntimalware_Scan(This,stream,result,provider) (This)->lpVtbl->Scan(This,stream,result,provider)
#define IAntimalware_CloseSession(This,session) (This)->lpVtbl->CloseSession(This,session)
#else
/*** IUnknown methods ***/
static FORCEINLINE HRESULT IAntimalware_QueryInterface(IAntimalware* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static FORCEINLINE ULONG IAntimalware_AddRef(IAntimalware* This) {
    return This->lpVtbl->AddRef(This);
}
static FORCEINLINE ULONG IAntimalware_Release(IAntimalware* This) {
    return This->lpVtbl->Release(This);
}
/*** IAntimalware methods ***/
static FORCEINLINE HRESULT IAntimalware_Scan(IAntimalware* This,IAmsiStream *stream,AMSI_RESULT *result,IAntimalwareProvider **provider) {
    return This->lpVtbl->Scan(This,stream,result,provider);
}
static FORCEINLINE void IAntimalware_CloseSession(IAntimalware* This,ULONGLONG session) {
    This->lpVtbl->CloseSession(This,session);
}
#endif
#endif

#endif


#endif  /* __IAntimalware_INTERFACE_DEFINED__ */

/*****************************************************************************
 * IAntimalware2 interface
 */
#ifndef __IAntimalware2_INTERFACE_DEFINED__
#define __IAntimalware2_INTERFACE_DEFINED__

DEFINE_GUID(IID_IAntimalware2, 0x301035b5, 0x2d42, 0x4f56, 0x8c,0x65, 0x2d,0xca,0xa7,0xfb,0x3c,0xdc);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("301035b5-2d42-4f56-8c65-2dcaa7fb3cdc")
IAntimalware2 : public IAntimalware
{
    virtual HRESULT STDMETHODCALLTYPE Notify(
        PVOID buffer,
        ULONG length,
        LPCWSTR contentName,
        LPCWSTR appName,
        AMSI_RESULT *pResult) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IAntimalware2, 0x301035b5, 0x2d42, 0x4f56, 0x8c,0x65, 0x2d,0xca,0xa7,0xfb,0x3c,0xdc)
#endif
#else
typedef struct IAntimalware2Vtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IAntimalware2 *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IAntimalware2 *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IAntimalware2 *This);

    /*** IAntimalware methods ***/
    HRESULT (STDMETHODCALLTYPE *Scan)(
        IAntimalware2 *This,
        IAmsiStream *stream,
        AMSI_RESULT *result,
        IAntimalwareProvider **provider);

    void (STDMETHODCALLTYPE *CloseSession)(
        IAntimalware2 *This,
        ULONGLONG session);

    /*** IAntimalware2 methods ***/
    HRESULT (STDMETHODCALLTYPE *Notify)(
        IAntimalware2 *This,
        PVOID buffer,
        ULONG length,
        LPCWSTR contentName,
        LPCWSTR appName,
        AMSI_RESULT *pResult);

    END_INTERFACE
} IAntimalware2Vtbl;

interface IAntimalware2 {
    CONST_VTBL IAntimalware2Vtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IAntimalware2_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IAntimalware2_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IAntimalware2_Release(This) (This)->lpVtbl->Release(This)
/*** IAntimalware methods ***/
#define IAntimalware2_Scan(This,stream,result,provider) (This)->lpVtbl->Scan(This,stream,result,provider)
#define IAntimalware2_CloseSession(This,session) (This)->lpVtbl->CloseSession(This,session)
/*** IAntimalware2 methods ***/
#define IAntimalware2_Notify(This,buffer,length,contentName,appName,pResult) (This)->lpVtbl->Notify(This,buffer,length,contentName,appName,pResult)
#else
/*** IUnknown methods ***/
static FORCEINLINE HRESULT IAntimalware2_QueryInterface(IAntimalware2* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static FORCEINLINE ULONG IAntimalware2_AddRef(IAntimalware2* This) {
    return This->lpVtbl->AddRef(This);
}
static FORCEINLINE ULONG IAntimalware2_Release(IAntimalware2* This) {
    return This->lpVtbl->Release(This);
}
/*** IAntimalware methods ***/
static FORCEINLINE HRESULT IAntimalware2_Scan(IAntimalware2* This,IAmsiStream *stream,AMSI_RESULT *result,IAntimalwareProvider **provider) {
    return This->lpVtbl->Scan(This,stream,result,provider);
}
static FORCEINLINE void IAntimalware2_CloseSession(IAntimalware2* This,ULONGLONG session) {
    This->lpVtbl->CloseSession(This,session);
}
/*** IAntimalware2 methods ***/
static FORCEINLINE HRESULT IAntimalware2_Notify(IAntimalware2* This,PVOID buffer,ULONG length,LPCWSTR contentName,LPCWSTR appName,AMSI_RESULT *pResult) {
    return This->lpVtbl->Notify(This,buffer,length,contentName,appName,pResult);
}
#endif
#endif

#endif


#endif  /* __IAntimalware2_INTERFACE_DEFINED__ */

#ifdef __cplusplus
class DECLSPEC_UUID("fdb00e52-a214-4aa1-8fba-4357bb0072ec") CAntimalware;
#endif
EXTERN_C const CLSID CLSID_Antimalware;

DECLARE_HANDLE(HAMSICONTEXT);
DECLARE_HANDLE(HAMSISESSION);

STDAPI AmsiInitialize(
    _In_  LPCWSTR appName,
    _Outptr_ HAMSICONTEXT* amsiContext);

STDAPI_(VOID) AmsiUninitialize(
    _In_  HAMSICONTEXT amsiContext);

STDAPI AmsiOpenSession(
    _In_  HAMSICONTEXT amsiContext,
    _Out_ HAMSISESSION* amsiSession);

STDAPI_(VOID) AmsiCloseSession(
    _In_  HAMSICONTEXT amsiContext,
    _In_  HAMSISESSION amsiSession);

STDAPI AmsiScanBuffer(
    _In_  HAMSICONTEXT amsiContext,
    _In_reads_bytes_(length) PVOID buffer,
    _In_  ULONG length,
    _In_opt_  LPCWSTR contentName,
    _In_opt_  HAMSISESSION amsiSession,
    _Out_ AMSI_RESULT* result);

STDAPI AmsiNotifyOperation(
    _In_  HAMSICONTEXT amsiContext,
    _In_reads_bytes_(length) PVOID buffer,
    _In_  ULONG length,
    _In_opt_  LPCWSTR contentName,
    _Out_ AMSI_RESULT* result);

STDAPI AmsiScanString(
    _In_  HAMSICONTEXT amsiContext,
    _In_  LPCWSTR string,
    _In_opt_  LPCWSTR contentName,
    _In_opt_  HAMSISESSION amsiSession,
    _Out_ AMSI_RESULT* result);

#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP) */
/* Begin additional prototypes for all interfaces */


/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __amsi_h__ */
