/*** Autogenerated by WIDL 5.0 from ./ccgplugins.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __ccgplugins_h__
#define __ccgplugins_h__

/* Forward declarations */

#ifndef __ICcgDomainAuthCredentials_FWD_DEFINED__
#define __ICcgDomainAuthCredentials_FWD_DEFINED__
typedef interface ICcgDomainAuthCredentials ICcgDomainAuthCredentials;
#ifdef __cplusplus
interface ICcgDomainAuthCredentials;
#endif /* __cplusplus */
#endif

/* Headers for imported files */

#include <oaidl.h>
#include <wtypes.h>

#ifdef __cplusplus
extern "C" {
#endif

/*****************************************************************************
 * ICcgDomainAuthCredentials interface
 */
#ifndef __ICcgDomainAuthCredentials_INTERFACE_DEFINED__
#define __ICcgDomainAuthCredentials_INTERFACE_DEFINED__

DEFINE_GUID(IID_ICcgDomainAuthCredentials, 0x6ecda518, 0x2010, 0x4437, 0x8b,0xc3, 0x46,0xe7,0x52,0xb7,0xb1,0x72);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("6ecda518-2010-4437-8bc3-46e752b7b172")
ICcgDomainAuthCredentials : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE GetPasswordCredentials(
        LPCWSTR pluginInput,
        LPWSTR *domainName,
        LPWSTR *username,
        LPWSTR *password) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(ICcgDomainAuthCredentials, 0x6ecda518, 0x2010, 0x4437, 0x8b,0xc3, 0x46,0xe7,0x52,0xb7,0xb1,0x72)
#endif
#else
typedef struct ICcgDomainAuthCredentialsVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        ICcgDomainAuthCredentials *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        ICcgDomainAuthCredentials *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        ICcgDomainAuthCredentials *This);

    /*** ICcgDomainAuthCredentials methods ***/
    HRESULT (STDMETHODCALLTYPE *GetPasswordCredentials)(
        ICcgDomainAuthCredentials *This,
        LPCWSTR pluginInput,
        LPWSTR *domainName,
        LPWSTR *username,
        LPWSTR *password);

    END_INTERFACE
} ICcgDomainAuthCredentialsVtbl;

interface ICcgDomainAuthCredentials {
    CONST_VTBL ICcgDomainAuthCredentialsVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define ICcgDomainAuthCredentials_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define ICcgDomainAuthCredentials_AddRef(This) (This)->lpVtbl->AddRef(This)
#define ICcgDomainAuthCredentials_Release(This) (This)->lpVtbl->Release(This)
/*** ICcgDomainAuthCredentials methods ***/
#define ICcgDomainAuthCredentials_GetPasswordCredentials(This,pluginInput,domainName,username,password) (This)->lpVtbl->GetPasswordCredentials(This,pluginInput,domainName,username,password)
#else
/*** IUnknown methods ***/
static FORCEINLINE HRESULT ICcgDomainAuthCredentials_QueryInterface(ICcgDomainAuthCredentials* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static FORCEINLINE ULONG ICcgDomainAuthCredentials_AddRef(ICcgDomainAuthCredentials* This) {
    return This->lpVtbl->AddRef(This);
}
static FORCEINLINE ULONG ICcgDomainAuthCredentials_Release(ICcgDomainAuthCredentials* This) {
    return This->lpVtbl->Release(This);
}
/*** ICcgDomainAuthCredentials methods ***/
static FORCEINLINE HRESULT ICcgDomainAuthCredentials_GetPasswordCredentials(ICcgDomainAuthCredentials* This,LPCWSTR pluginInput,LPWSTR *domainName,LPWSTR *username,LPWSTR *password) {
    return This->lpVtbl->GetPasswordCredentials(This,pluginInput,domainName,username,password);
}
#endif
#endif

#endif


#endif  /* __ICcgDomainAuthCredentials_INTERFACE_DEFINED__ */

/* Begin additional prototypes for all interfaces */


/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __ccgplugins_h__ */
