/*** Autogenerated by WIDL 7.0-rc1 from ./remotesystemadditionalinfo.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __remotesystemadditionalinfo_h__
#define __remotesystemadditionalinfo_h__

/* Forward declarations */

#ifndef __IRemoteSystemAdditionalInfoProvider_FWD_DEFINED__
#define __IRemoteSystemAdditionalInfoProvider_FWD_DEFINED__
typedef interface IRemoteSystemAdditionalInfoProvider IRemoteSystemAdditionalInfoProvider;
#ifdef __cplusplus
interface IRemoteSystemAdditionalInfoProvider;
#endif /* __cplusplus */
#endif

/* Headers for imported files */

#include <unknwn.h>
#include <hstring.h>

#ifdef __cplusplus
extern "C" {
#endif

#include <winapifamily.h>
#if (NTDDI_VERSION >= NTDDI_WIN10_RS4)
#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP)
/*****************************************************************************
 * IRemoteSystemAdditionalInfoProvider interface
 */
#ifndef __IRemoteSystemAdditionalInfoProvider_INTERFACE_DEFINED__
#define __IRemoteSystemAdditionalInfoProvider_INTERFACE_DEFINED__

DEFINE_GUID(IID_IRemoteSystemAdditionalInfoProvider, 0xeeaa3d5f, 0xec63, 0x4d27, 0xaf,0x38, 0xe8,0x6b,0x1d,0x72,0x92,0xcb);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("eeaa3d5f-ec63-4d27-af38-e86b1d7292cb")
IRemoteSystemAdditionalInfoProvider : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE GetAdditionalInfo(
        HSTRING *deduplicationId,
        REFIID riid,
        void **mapView) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IRemoteSystemAdditionalInfoProvider, 0xeeaa3d5f, 0xec63, 0x4d27, 0xaf,0x38, 0xe8,0x6b,0x1d,0x72,0x92,0xcb)
#endif
#else
typedef struct IRemoteSystemAdditionalInfoProviderVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IRemoteSystemAdditionalInfoProvider *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IRemoteSystemAdditionalInfoProvider *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IRemoteSystemAdditionalInfoProvider *This);

    /*** IRemoteSystemAdditionalInfoProvider methods ***/
    HRESULT (STDMETHODCALLTYPE *GetAdditionalInfo)(
        IRemoteSystemAdditionalInfoProvider *This,
        HSTRING *deduplicationId,
        REFIID riid,
        void **mapView);

    END_INTERFACE
} IRemoteSystemAdditionalInfoProviderVtbl;

interface IRemoteSystemAdditionalInfoProvider {
    CONST_VTBL IRemoteSystemAdditionalInfoProviderVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IRemoteSystemAdditionalInfoProvider_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IRemoteSystemAdditionalInfoProvider_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IRemoteSystemAdditionalInfoProvider_Release(This) (This)->lpVtbl->Release(This)
/*** IRemoteSystemAdditionalInfoProvider methods ***/
#define IRemoteSystemAdditionalInfoProvider_GetAdditionalInfo(This,deduplicationId,riid,mapView) (This)->lpVtbl->GetAdditionalInfo(This,deduplicationId,riid,mapView)
#else
/*** IUnknown methods ***/
static FORCEINLINE HRESULT IRemoteSystemAdditionalInfoProvider_QueryInterface(IRemoteSystemAdditionalInfoProvider* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static FORCEINLINE ULONG IRemoteSystemAdditionalInfoProvider_AddRef(IRemoteSystemAdditionalInfoProvider* This) {
    return This->lpVtbl->AddRef(This);
}
static FORCEINLINE ULONG IRemoteSystemAdditionalInfoProvider_Release(IRemoteSystemAdditionalInfoProvider* This) {
    return This->lpVtbl->Release(This);
}
/*** IRemoteSystemAdditionalInfoProvider methods ***/
static FORCEINLINE HRESULT IRemoteSystemAdditionalInfoProvider_GetAdditionalInfo(IRemoteSystemAdditionalInfoProvider* This,HSTRING *deduplicationId,REFIID riid,void **mapView) {
    return This->lpVtbl->GetAdditionalInfo(This,deduplicationId,riid,mapView);
}
#endif
#endif

#endif


#endif  /* __IRemoteSystemAdditionalInfoProvider_INTERFACE_DEFINED__ */

#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP) */
#endif /* (NTDDI_VERSION >= NTDDI_WIN10_RS4) */
/* Begin additional prototypes for all interfaces */

ULONG           __RPC_USER HSTRING_UserSize     (ULONG *, ULONG, HSTRING *);
unsigned char * __RPC_USER HSTRING_UserMarshal  (ULONG *, unsigned char *, HSTRING *);
unsigned char * __RPC_USER HSTRING_UserUnmarshal(ULONG *, unsigned char *, HSTRING *);
void            __RPC_USER HSTRING_UserFree     (ULONG *, HSTRING *);

/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __remotesystemadditionalinfo_h__ */
